/**
 * Ambient declarations for the "magic" constants generated by Electron Forge's
 * Webpack plugin. They tell the main process where the bundled renderer entry
 * and preload script live, differing between dev and production builds.
 *
 * One pair of constants is declared per `entryPoints` name in forge.config.ts.
 * Our single window is named `main_window`.
 */
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
